export default {
    id: 'cs2',
    name: 'Counter-Strike 2',
    icon: 'cs2/knife.svg',
    keys: [
        { id: 'move_forward', label: "Move Forward", short: "forward" },
        { id: 'move_backward', label: "Move Backward", short: "back" },
        { id: 'move_left', label: "Strafe Left", short: "left" },
        { id: 'move_right', label: "Strafe Right", short: "right" },
        { id: 'move_jump', label: "Jump" },
        { id: 'move_walk', label: "Walk" },
        { id: 'move_crouch', label: "Duck" },

        { id: 'gun_fire', label: "Fire" },
        { id: 'gun_scope', label: "Scope" },
        { id: 'gun_reload', label: "Reload" },

        { id: 'chat_say', label: "Chat", short: "chat" },
        { id: 'chat_wheel1', label: "Chat Wheel 1", short: "cw1" },
        { id: 'chat_wheel2', label: "Chat Wheel 2", short: "cw2" },
        { id: 'chat_wheel3', label: "Chat Wheel 3", short: "cw3" },
        { id: 'chat_mark', label: "Mark" },
        { id: 'chat_voice', label: "Use Microphone", short: "mic" },

        { id: 'inv_buy', label: "Buy" },
        { id: 'inv_drop', label: "Drop Item", short: "drop" },
        { id: 'inv_last', label: "Last Weapon Used", short: "last" },
        { id: 'inv_grenade', label: "Cycle Grenades", short: "grenade" },

        { id: 'misc_use', label: "Use" },
        { id: 'misc_score', label: "Scoreboard", short: "score" },
        { id: 'misc_switchteam', label: "Switch Team", short: "team" },
        { id: 'misc_switchhand', label: "Switch Viewmodel Hand", short: "hand" },
        { id: 'misc_inspect', label: "Inspect Weapon", short: "inspect" },
    ],
    groups: [
        { id: 'move', name: "Movement", color: "blue" },
        { id: 'inv', name: "Inventory", color: "purple" },
        { id: 'gun', name: "Gun", color: "orange" },
        { id: 'chat', name: "Chat", color: "cyan" },
        { id: 'misc', name: "Misc", color: "grey" },
    ],
    hotbarSize: 10,
    hotbarKeysColor: 'green',
    canEditHotbar: false,
    hotbarItems: [
        { id: 'primary', label: "Primary Gun", icon: 'cs2/ak.svg' },
        { id: 'pistol', label: "Pistol", icon: 'cs2/p250.svg' },
        { id: 'knife', label: "Knife", icon: 'cs2/knife.svg' },
        { id: 'c4', label: "C4", icon: 'cs2/c4.svg' },
        { id: 'flash', label: "Flashbang", icon: 'cs2/flashbang.svg' },
        { id: 'smoke', label: "Smoke Grenade", icon: 'cs2/smokegrenade.svg' },
        { id: 'he', label: "HE Grenade", icon: 'cs2/hegrenade.svg' },
        { id: 'molotov', label: "Molotov / Incendiary", icon: 'cs2/molotov.svg' },
        { id: 'decoy', label: "Decoy Grenade", icon: 'cs2/decoy.svg' },
        { id: 'zeus', label: "Zeus x27", icon: 'cs2/taser.svg' },
    ],
    hotbarSpacers: [3, 9],
    defaultBinds: {
        w: 'move_forward',
        a: 'move_left',
        s: 'move_backward',
        d: 'move_right',
        lmb: 'gun_fire',
        rmb: 'gun_scope',
        r: 'gun_reload',
        space: 'move_jump',
        b: 'inv_buy',
        shiftleft: 'move_walk',
        ctrlleft: 'move_crouch',
        tab: 'misc_score',
    }
}