import { type Game } from "../types";

export default {
    id: 'rust',
    name: 'Rust',
    icon: 'rust/rust.svg',
    keys: [
        { id: 'move_forward', label: "Move Forward", short: "forward" },
        { id: 'move_backward', label: "Move Backward", short: "back" },
        { id: 'move_left', label: "Strafe Left", short: "left" },
        { id: 'move_right', label: "Strafe Right", short: "right" },
        { id: 'move_jump', label: "Jump" },
        { id: 'move_sprint', label: "Sprint" },
        { id: 'move_crouch', label: "Duck" },
        { id: 'move_autowalk', label: "Auto walk", short: "autowalk" },

        { id: 'actions_pri', label: "Primary Attack", short: "primary" },
        { id: 'actions_sec', label: "Secondary Attack", short: "secondary" },
        { id: 'actions_use', label: "Use" },
        { id: 'actions_reload', label: "Reload" },
        { id: 'actions_headlook', label: "Head look", short: "headlook" },
        { id: 'actions_light', label: "Light Toggle", short: "light" },
        { id: 'actions_firemode', label: "Fire Mode", short: "firemode" },
        { id: 'actions_examine', label: "Examine Held Item", short: "examine" },
        { id: 'actions_gesture', label: "Gesture", short: "gesture" },
        { id: 'actions_ping', label: "Ping", short: "ping" },
        { id: 'actions_switchzoom', label: "Switch Zoom", short: "switchzoom" },
        { id: 'actions_increasezoom', label: "Increase Zoom", short: "zoom+" },
        { id: 'actions_decreasezoom', label: "Decrease Zoom", short: "zoom-" },

        { id: 'coms_voice', label: "Voice Transmit", short: "voice" },
        { id: 'coms_chat', label: "Chat", short: "chat" },

        { id: 'inv_open', label: "Inventory", short: "inv" },
        { id: 'inv_craft', label: "Crafting Menu", short: "craft" },
        { id: 'inv_holster', label: "Holster Item", short: "holster" },
        { id: 'inv_dropsingle', label: "Drop Item (Single)", short: "drop1" },
        { id: 'inv_dropall', label: "Drop Item (Stack)", short: "dropstack" },
        { id: 'inv_directionaldrop', label: "Directional Drop", short: "dropdir" },
        { id: 'inv_hoverloot', label: "Hover Loot", short: "hoverloot" },

        { id: 'vehicle_seat', label: "Change Vehicle Seat", short: "changeseat" },
        { id: 'vehicle_seat1', label: "Driver Seat", short: "seat1" },
        { id: 'vehicle_seat2', label: "Seat 2", short: "seat2" },
        { id: 'vehicle_seat3', label: "Seat 3", short: "seat3" },
        { id: 'vehicle_seat4', label: "Seat 4", short: "seat4" },
        { id: 'vehicle_seat5', label: "Seat 5", short: "seat5" },
        { id: 'vehicle_seat6', label: "Seat 6", short: "seat6" },
        { id: 'vehicle_seat7', label: "Seat 7", short: "seat7" },
        { id: 'vehicle_seat8', label: "Seat 8", short: "seat8" },

        { id: 'map_show', label: "Map", short: "map" },
        { id: 'map_marker', label: "Add Map Marker", short: "mapmarker" },
        { id: 'map_clearmark', label: "Clear All Map Markers", short: "clearmark" },
        { id: 'map_player', label: "Focus Map on Player", short: "mapplayer" },
        { id: 'map_compass', label: "Compass", short: "compass" },

        { id: 'ctxm_prev', label: "Previous Skin", short: "ctxprev" },
        { id: 'ctxm_next', label: "Next Skin", short: "ctxnext" },

        { id: 'inst_a', label: "A Note", short: "a" },
        { id: 'inst_as', label: "A# Note", short: "a#" },
        { id: 'inst_g', label: "G Note", short: "g" },
        { id: 'inst_gs', label: "G# Note", short: "g#" },
        { id: 'inst_c', label: "C Note", short: "c" },
        { id: 'inst_cs', label: "C# Note", short: "c#" },
        { id: 'inst_d', label: "D Note", short: "d" },
        { id: 'inst_ds', label: "D# Note", short: "d#" },
        { id: 'inst_e', label: "E Note", short: "e" },
        { id: 'inst_es', label: "E# Note", short: "e#" },
        { id: 'inst_f', label: "F Note", short: "f" },
        { id: 'inst_fs', label: "F# Note", short: "f#" },
        { id: 'inst_b', label: "B Note", short: "b" },
        { id: 'inst_bs', label: "B# Note", short: "b#" },
        { id: 'inst_sharp', label: "Sharp Note", short: "sharp" },
        { id: 'inst_octave', label: "Octave Up", short: "octave" },

        { id: 'misc_incwire', label: "Increase Wire Slack", short: "slack+" },
        { id: 'misc_decwire', label: "Decrease Wire Slack", short: "slack-" },
        { id: 'misc_pets', label: "Pets", short: "pets" },
        { id: 'misc_dev', label: "Developer Console", short: "dev" },
    ],
    groups: [
        { id: 'move', name: "Movement", color: "blue" },
        { id: 'inv', name: "Inventory", color: "purple" },
        { id: 'actions', name: "Actions", color: "orange" },
        { id: 'coms', name: "Communication", color: "cyan" },
        { id: 'map', name: "Map", color: "red" },
        { id: 'vehicle', name: "Vehicle", color: "yellow" },
        { id: 'misc', name: "Misc", color: "grey" },
    ],
    hotbarSize: 6,
    hotbarKeysColor: 'green',
    canEditHotbar: false,
    hotbarItems: [
        { id: 'slot1', label: "Slot 1", icon: 'rust/1.svg' },
        { id: '2', label: "Slot 2", icon: 'rust/2.svg' },
        { id: '3', label: "Slot 3", icon: 'rust/3.svg' },
        { id: '4', label: "Slot 4", icon: 'rust/4.svg' },
        { id: '5', label: "Slot 5", icon: 'rust/5.svg' },
        { id: '6', label: "Slot 6", icon: 'rust/6.svg' },
    ],
    hotbarSpacers: [],
    defaultBinds: {
        w: 'move_forward',
        a: 'move_left',
        s: 'move_backward',
        d: 'move_right',
        shiftleft: 'move_sprint',
        ctrlleft: 'move_crouch',
        space: 'move_jump',
        lmb: 'actions_pri',
        rmb: 'actions_sec',
        e: 'actions_use',
        r: 'gun_reload',
        altleft: 'actions_headlook',
        f: 'actions_light',
        m: 'actions_firemode',
        n: 'actions_examine',
        b: 'actions_gesture',
        mb4: 'actions_ping',
        pageup: 'actions_increasezoom',
        pagedown: 'actions_decreasezoom',
        v: 'coms_voice',
        enter: 'coms_chat',
        t: 'coms_chat',
        tab: 'inv_open',
        q: 'inv_craft',
        _7: 'inv_holster',
        h: 'inv_hoverloot',
        x: 'vehicle_seat',
        g: 'map_show',
        c: 'compass',
        p: 'misc_pets',
        f1: 'misc_dev',
    }
} as Game;